### ISSUE TITLE
two kinds of googleapis are used and WrapError doesn't return apierror.APIError

### ISSUE THREAD

**Issue by ledmonster** [ClearBlade/go-iot#15]
While `iot.go` uses
- "github.com/clearblade/go-iot/cblib/googleapi"

`cblib.gensupport` uses
- "google.golang.org/api/googleapi"

Because of this problem, gensupports' `WrapError` doesn't return `apierror.APIError`. Following test faiils.

```
call := c.iot.Projects.Locations.Registries.Devices.Get(c.devicePath(deviceID)).Context(c.ctx)
_, err := call.Do()
e, ok := err.(*apierror.APIError)
if !ok {
	t.Fatalf("expect apierror.APIError type. err: %v", err)
}
```

Please use either of these two module.

**Comment by ledmonster** [comment]
It seems that I misunderstood. `call.Do()` doesn't return `googleapi.Error`. It returns custom error generated here.
- https://github.com/ClearBlade/go-iot/blob/main/iot.go#L112

But I think it's still confusing.

**Comment by andrewhdev** [comment]
Thank you for taking the time to open this ticket.

I'd like to clarify a couple of things about your request:
- Are you requesting a specific change to the call.Do() error response or an improvement to our documentation about errors?
- Did this test previously work with Google's iot core sdk, but now fails when using ClearBlade's sdk?

**Comment by ledmonster** [comment]
> Did this test previously work with Google's iot core sdk, but now fails when using ClearBlade's sdk?

following test works with Google's iot core sdk (`google.golang.org/api v0.107.0`).

```
call := c.iot.Projects.Locations.Registries.Devices.Get(c.devicePath(deviceID)).Context(c.ctx)
_, err := call.Do()
e, ok := err.(*googleapi.Error)
if !ok {
	t.Fatal("expect googleapi.Error type")
}
```
`call.Do()` returns `googleapi.Error`. (not `apierror.APIError`).

On the other hand, clearblade implementation returns `errors.New(..)` object.


> Are you requesting a specific change to the call.Do() error response or an improvement to our documentation about errors?

I request two things.
- I want you to use either `google.golang.org/api/googleapi` or `github.com/clearblade/go-iot/cblib/googleapi`. Please don't use both.
- I want `call.Do()` to return `googleapi.Error` object, which has much more detail than normal `errors.New(..)` object.

**Comment by andrewhdev** [comment]
Thank you for the clarifications. I'll keep you updated on the progress of these changes.

**Comment by andrewhdev** [comment]
@ledmonster I have opened this PR to hopefully resolve your issue: https://github.com/ClearBlade/go-iot/pull/16

You can install this change to your project using the command: `go get github.com/clearblade/go-iot@716cfcbdcd955d2af679d6fbb3c575425ff3d480`

Would you please verify that this change is what you requested?

**Comment by ledmonster** [comment]
@andrewhdev it works fine, thank you!!
