### ISSUE TITLE
Duplicates when listing devices

### ISSUE THREAD

**Issue by rubenvannieuwpoort** [ClearBlade/go-iot#30]
We run a daily job that retrieves between 700 and 800 devices with the `Service.Projects.Locations.Registries.Devices.List` call. We use a page size of 100, so we send out 8 requests in total.

In about 10% of the job runs we see that there are some devices duplicated while others are missing. I have debugged a few cases and so far the duplicates were always of this form:
  - Page N contains device `abc`
  - The first device of page N + 1 also contains device `abc`

This seems to indicate a bug in the pagination.

I have also looked at the responses from the backend, and I see the duplicates there too, so this might be a backend issue (instead of being an issue in this client), but I am not 100% sure. Since the observed issue is with the client (and also I wouldn't know where to report problems with the backend, which I assume is internal), I am reporting it here.

I have tried working around the issue by setting the page size to a much larger number and this seems to work (but it's based on very limited testing so I don't know how robust this is, and now that I think of it, I have only tested for duplicates, and assumed that no duplicates also means no missing devices).

We have observed the behavior in versions `v1.0.11` and `v1.0.12` (I haven't tested on older versions).

**Comment by sky-sharma** [comment]
@rubenvannieuwpoort thank you for bringing this to our attention. Can you please file a ticket here and provide some details and we will investigate:

https://clearblade.atlassian.net/servicedesk/customer/portal/1/group/1/create/20

Thanks!

**Comment by rubenvannieuwpoort** [comment]
Thank you for your reply! I have reported this.

It sounds like it is not an issue with the `go-iot` client but rather in the backend, so I will close this issue.
